defmodule CryptoHustler.DataMergerTest do
  use ExUnit.Case, async: true

  alias Bittrex.Data.{Currency, Market, MarketSummary, Ticker}
  alias CryptoHustler.DataCombiner

  test "combines currencies with markets" do
    currencies = [%Currency{
      active: true,
      base_address: "1N52wHoVR79PMDishab2XmRHsbekCdGquK",
      code: "BTC",
      coin_type: "BITCOIN",
      minimum_confirmation: 2,
      name: "Bitcoin",
      transaction_fee: 0.001,
    }, %Currency{
      active: true,
      base_address: "0xfbb1b73c4f0bda4f67dca266ce6ef42f520fbb98",
      code: "ETH",
      coin_type: "ETH",
      minimum_confirmation: 36,
      name: "Ethereum",
      transaction_fee: 0.002
    }, %Currency{
      active: true,
      base_address: "LhyLNfBkoKshT7R8Pce6vkB9T2cP2o84hx",
      code: "LTC",
      coin_type: "BITCOIN",
      minimum_confirmation: 6,
      name: "Litecoin",
      transaction_fee: 0.01,
    }, %Currency{
      active: false,
      base_address: nil,
      code: "OC",
      coin_type: "BITCOIN",
      minimum_confirmation: 20,
      name: "OrangeCoin",
      transaction_fee: 0.2,
    }]
    markets = [%Market{
      active: true,
      base_currency: %Currency{
        active: true,
        base_address: nil,
        code: "BTC",
        coin_type: nil,
        minimum_confirmation: nil,
        name: "Bitcoin",
        transaction_fee: nil,
      },
      created_at: ~N[2014-02-13 00:00:00],
      market_currency: %Currency{
        active: true,
        base_address: nil,
        code: "LTC",
        coin_type: nil,
        minimum_confirmation: nil,
        name: "Litecoin",
        transaction_fee: nil,
      },
      minimum_trade: 0.02739726,
      name: "BTC-LTC",
    }, %Market{
      active: true,
      base_currency: %Currency{
        active: true,
        base_address: nil,
        code: "ETH",
        coin_type: nil,
        minimum_confirmation: nil,
        name: "Ethereum",
        transaction_fee: nil,
      },
      created_at: ~N[2017-06-25 03:06:46.83],
      market_currency: %Currency{
        active: true,
        base_address: nil,
        code: "LTC",
        coin_type: nil,
        minimum_confirmation: nil,
        name: "Litecoin",
        transaction_fee: nil,
      },
      minimum_trade: 0.02272626,
      name: "ETH-LTC",
    }, %Market{
      active: true,
      base_currency: %Currency{
        active: true,
        base_address: nil,
        code: "USDT",
        coin_type: nil,
        minimum_confirmation: nil,
        name: "Tether",
        transaction_fee: nil,
      },
      created_at: ~N[2017-07-14 17:10:10.72],
      market_currency: %Currency{
        active: true,
        base_address: nil,
        code: "LTC",
        coin_type: nil,
        minimum_confirmation: nil,
        name: "Litecoin",
        transaction_fee: nil,
      },
      minimum_trade: 0.02980626,
      name: "USDT-LTC",
    }, %Market{
      active: true,
      base_currency: %Currency{
        active: true,
        base_address: nil,
        code: "BTC",
        coin_type: nil,
        minimum_confirmation: nil,
        name: "Bitcoin",
        transaction_fee: nil,
      },
      created_at: ~N[2014-08-20 07:09:57.207],
      market_currency: %Currency{
        active: true,
        base_address: nil,
        code: "DGB",
        coin_type: nil,
        minimum_confirmation: nil,
        name: "Digibyte",
        transaction_fee: nil,
      },
      minimum_trade: 225.22522523,
      name: "BTC-DGB",
    }, ]

    assert [%Market{
      active: true,
      base_currency: %Currency{
        active: true,
        base_address: "0xfbb1b73c4f0bda4f67dca266ce6ef42f520fbb98",
        code: "ETH",
        coin_type: "ETH",
        minimum_confirmation: 36,
        name: "Ethereum",
        transaction_fee: 0.002
      },
      created_at: ~N[2017-06-25 03:06:46.83],
      market_currency: %Currency{
        active: true,
        base_address: "LhyLNfBkoKshT7R8Pce6vkB9T2cP2o84hx",
        code: "LTC",
        coin_type: "BITCOIN",
        minimum_confirmation: 6,
        name: "Litecoin",
        transaction_fee: 0.01,
      },
      minimum_trade: 0.02272626,
      name: "ETH-LTC",
    }, %Market{
      active: true,
      base_currency: %Currency{
        active: true,
        base_address: "1N52wHoVR79PMDishab2XmRHsbekCdGquK",
        code: "BTC",
        coin_type: "BITCOIN",
        minimum_confirmation: 2,
        name: "Bitcoin",
        transaction_fee: 0.001,
      },
      created_at: ~N[2014-02-13 00:00:00],
      market_currency: %Currency{
        active: true,
        base_address: "LhyLNfBkoKshT7R8Pce6vkB9T2cP2o84hx",
        code: "LTC",
        coin_type: "BITCOIN",
        minimum_confirmation: 6,
        name: "Litecoin",
        transaction_fee: 0.01,
      },
      minimum_trade: 0.02739726,
      name: "BTC-LTC",
    }] = DataCombiner.combine_currencies_with_markets(currencies, markets)
  end

  test "combines markets with market summaries" do
    markets = [%Market{
      active: true,
      base_currency: %Currency{
        active: true,
        base_address: nil,
        code: "BTC",
        coin_type: nil,
        minimum_confirmation: nil,
        name: "Bitcoin",
        transaction_fee: nil,
      },
      created_at: ~N[2014-02-13 00:00:00],
      market_currency: %Currency{
        active: true,
        base_address: nil,
        code: "LTC",
        coin_type: nil,
        minimum_confirmation: nil,
        name: "Litecoin",
        transaction_fee: nil,
      },
      minimum_trade: 0.02739726,
      name: "BTC-LTC",
    }, %Market{
      active: true,
      base_currency: %Currency{
        active: true,
        base_address: nil,
        code: "ETH",
        coin_type: nil,
        minimum_confirmation: nil,
        name: "Ethereum",
        transaction_fee: nil,
      },
      created_at: ~N[2017-06-25 03:06:46.83],
      market_currency: %Currency{
        active: true,
        base_address: nil,
        code: "LTC",
        coin_type: nil,
        minimum_confirmation: nil,
        name: "Litecoin",
        transaction_fee: nil,
      },
      minimum_trade: 0.02272626,
      name: "ETH-LTC",
    }, %Market{
      active: true,
      base_currency: %Currency{
        active: true,
        base_address: nil,
        code: "USDT",
        coin_type: nil,
        minimum_confirmation: nil,
        name: "Tether",
        transaction_fee: nil,
      },
      created_at: ~N[2017-07-14 17:10:10.72],
      market_currency: %Currency{
        active: true,
        base_address: nil,
        code: "LTC",
        coin_type: nil,
        minimum_confirmation: nil,
        name: "Litecoin",
        transaction_fee: nil,
      },
      minimum_trade: 0.02980626,
      name: "USDT-LTC",
    }]
    market_summaries = [%MarketSummary{
      base_volume: 2175.28765307,
      high: 0.0071864,
      low: 0.00541977,
      market: %Market{
        active: nil,
        base_currency: %Currency{
          active: nil,
          base_address: nil,
          code: nil,
          coin_type: nil,
          minimum_confirmation: nil,
          name: nil,
          transaction_fee: nil,
        },
        created_at: ~N[2014-02-13 00:00:00],
        market_currency: %Currency{
          active: nil,
          base_address: nil,
          code: nil,
          coin_type: nil,
          minimum_confirmation: nil,
          name: nil,
          transaction_fee: nil,
        },
        minimum_trade: nil,
        name: "BTC-LTC",
      },
      open_buy_orders: 781,
      open_sell_orders: 12717,
      previous_day: 0.00695001,
      ticker: %Ticker{
        ask: 0.0056499,
        bid: 0.00564513,
        last: 0.00564513,
      },
      volume: 346395.83380601,
    }, %MarketSummary{
      base_volume: 3625.74616162,
      high: 0.23753,
      low: 0.21423654,
      market: %Market{
        active: nil,
        base_currency: %Currency{
          active: nil,
          base_address: nil,
          code: nil,
          coin_type: nil,
          minimum_confirmation: nil,
          name: nil,
          transaction_fee: nil,
        },
        created_at: ~N[2017-06-25 03:06:46.83],
        market_currency: %Currency{
          active: nil,
          base_address: nil,
          code: nil,
          coin_type: nil,
          minimum_confirmation: nil,
          name: nil,
          transaction_fee: nil,
        },
        minimum_trade: nil,
        name: "ETH-LTC",
      },
      open_buy_orders: 428,
      open_sell_orders: 241,
      previous_day: 0.23292222,
      ticker: %Ticker{
        ask: 0.22780449,
        bid: 0.22531679,
        last: 0.22780477,
      },
      volume: 16008.79128839,
    }, %MarketSummary{
      base_volume: 7045511.12100312,
      high: 98.0,
      low: 85.6896,
      market: %Market{
        active: nil,
        base_currency: %Currency{
          active: nil,
          base_address: nil,
          code: nil,
          coin_type: nil,
          minimum_confirmation: nil,
          name: nil,
          transaction_fee: nil,
        },
        created_at: ~N[2017-07-14 17:10:10.72],
        market_currency: %Currency{
          active: nil,
          base_address: nil,
          code: nil,
          coin_type: nil,
          minimum_confirmation: nil,
          name: nil,
          transaction_fee: nil,
        },
        minimum_trade: nil,
        name: "USDT-LTC",
      },
      open_buy_orders: 1209,
      open_sell_orders: 1473,
      previous_day: 94.20000002,
      ticker: %Ticker{
        ask: 91.36399992,
        bid: 90.89,
        last: 90.89519998,
      },
      volume: 76753.99773865,
    }, %MarketSummary{
      base_volume: 39.55762541,
      high: 2.824e-5,
      low: 1.8e-5,
      market: %Market{
        active: nil,
        base_currency: %Currency{
          active: nil,
          base_address: nil,
          code: nil,
          coin_type: nil,
          minimum_confirmation: nil,
          name: nil,
          transaction_fee: nil,
        },
        created_at: ~N[2017-06-06 01:22:35.727],
        market_currency: %Currency{
          active: nil,
          base_address: nil,
          code: nil,
          coin_type: nil,
          minimum_confirmation: nil,
          name: nil,
          transaction_fee: nil
        },
        minimum_trade: nil,
        name: "BTC-1ST"
      },
      open_buy_orders: 79,
      open_sell_orders: 3498,
      previous_day: 2.738e-5,
      ticker: %Ticker{
        ask: 2.325e-5,
        bid: 2.277e-5,
        last: 2.275e-5
      },
      volume: 1790098.90279788
    }]

    assert [%MarketSummary{
      base_volume: 7045511.12100312,
      high: 98.0,
      low: 85.6896,
      market: %Market{
        active: true,
        base_currency: %Currency{
          active: true,
          base_address: nil,
          code: "USDT",
          coin_type: nil,
          minimum_confirmation: nil,
          name: "Tether",
          transaction_fee: nil,
        },
        created_at: ~N[2017-07-14 17:10:10.72],
        market_currency: %Currency{
          active: true,
          base_address: nil,
          code: "LTC",
          coin_type: nil,
          minimum_confirmation: nil,
          name: "Litecoin",
          transaction_fee: nil,
        },
        minimum_trade: 0.02980626,
        name: "USDT-LTC",
      },
      open_buy_orders: 1209,
      open_sell_orders: 1473,
      previous_day: 94.20000002,
      ticker: %Ticker{
        ask: 91.36399992,
        bid: 90.89,
        last: 90.89519998,
      },
      volume: 76753.99773865,
    }, %MarketSummary{
      base_volume: 3625.74616162,
      high: 0.23753,
      low: 0.21423654,
      market: %Market{
        active: true,
        base_currency: %Currency{
          active: true,
          base_address: nil,
          code: "ETH",
          coin_type: nil,
          minimum_confirmation: nil,
          name: "Ethereum",
          transaction_fee: nil,
        },
        created_at: ~N[2017-06-25 03:06:46.83],
        market_currency: %Currency{
          active: true,
          base_address: nil,
          code: "LTC",
          coin_type: nil,
          minimum_confirmation: nil,
          name: "Litecoin",
          transaction_fee: nil,
        },
        minimum_trade: 0.02272626,
        name: "ETH-LTC",
      },
      open_buy_orders: 428,
      open_sell_orders: 241,
      previous_day: 0.23292222,
      ticker: %Ticker{
        ask: 0.22780449,
        bid: 0.22531679,
        last: 0.22780477,
      },
      volume: 16008.79128839,
    }, %MarketSummary{
      base_volume: 2175.28765307,
      high: 0.0071864,
      low: 0.00541977,
      market: %Market{
        active: true,
        base_currency: %Currency{
          active: true,
          base_address: nil,
          code: "BTC",
          coin_type: nil,
          minimum_confirmation: nil,
          name: "Bitcoin",
          transaction_fee: nil,
        },
        created_at: ~N[2014-02-13 00:00:00],
        market_currency: %Currency{
          active: true,
          base_address: nil,
          code: "LTC",
          coin_type: nil,
          minimum_confirmation: nil,
          name: "Litecoin",
          transaction_fee: nil,
        },
        minimum_trade: 0.02739726,
        name: "BTC-LTC",
      },
      open_buy_orders: 781,
      open_sell_orders: 12717,
      previous_day: 0.00695001,
      ticker: %Ticker{
        ask: 0.0056499,
        bid: 0.00564513,
        last: 0.00564513,
      },
      volume: 346395.83380601,
    }] = DataCombiner.combine_markets_with_market_summaries(markets, market_summaries)
  end
end
