defmodule CryptoHustler.MarketFilterTest do
  use ExUnit.Case, async: true

  alias Bittrex.Data.{Balance, Currency, Market, MarketSummary, Order, Ticker}
  alias CryptoHustler.MarketFilter

  test "filters BTC markets" do
    assert [%MarketSummary{
      market: %Market{
        name: "BTC-ZEC",
      },
    }] = MarketFilter.filter(market_summaries(), "BTC", balances(), open_orders())
  end

  test "filters USDT markets" do
    assert [%MarketSummary{
      market: %Market{
        name: "USDT-ZEC",
      },
    }] = MarketFilter.filter(market_summaries(), "USDT", balances(), open_orders())
  end

  defp balances do
    [%Balance{
      available: 0.00000003,
      balance: 0.00000003,
      currency: %Currency{
        code: "BTC",
      },
    }, %Balance{
      available: 0.0,
      balance: 0.00779119,
      currency: %Currency{
        code: "BTG",
      },
    }, %Balance{
      available: 76.42821529,
      balance: 76.42821529,
      currency: %Currency{
        code: "NXT",
      },
    }, %Balance{
      available: 0.0,
      balance: 0.0,
      currency: %Currency{
        code: "XRP",
      },
    }]
  end

  defp market_summaries do
    [%MarketSummary{
      base_volume: 1891656.01431634,
      high: 330.0,
      low: 275.0,
      market: %Market{
        active: true,
        base_currency: %Currency{
          active: true,
          base_address: "1DUb2YYbQA1jjaNYzVXLZ7ZioEhLXtbUru",
          code: "USDT",
          coin_type: "OMNI",
          minimum_confirmation: 2,
          name: "Tether",
          transaction_fee: 5.0,
        },
        created_at: ~N[2017-07-14 17:10:10.673],
        market_currency: %Currency{
          active: true,
          base_address: "t1KVcK1PEFHRjzJTA3oeXA82tiUGj5V72Cb",
          code: "ZEC",
          coin_type: "BITCOINEX",
          minimum_confirmation: 20,
          name: "ZCash",
          transaction_fee: 0.005,
        },
        minimum_trade: 0.0093059,
        name: "USDT-ZEC",
      },
      open_buy_orders: 710,
      open_sell_orders: 2665,
      previous_day: 282.12,
      ticker: %Ticker{
        ask: 319.09624055,
        bid: 317.10000002,
        last: 317.1,
      },
      volume: 6249.82867895,
    }, %MarketSummary{
      base_volume: 48.64764139,
      high: 3.882e-5,
      low: 2.723e-5,
      market: %Market{
        active: true,
        base_currency: %Currency{
          active: true,
          base_address: "1N52wHoVR79PMDishab2XmRHsbekCdGquK",
          code: "BTC",
          coin_type: "BITCOIN",
          minimum_confirmation: 2,
          name: "Bitcoin",
          transaction_fee: 0.001,
        },
        created_at: ~N[2016-01-18 20:38:22.707],
        market_currency: %Currency{
          active: false,
          base_address: "1DUb2YYbQA1jjaNYzVXLZ7ZioEhLXtbUru",
          code: "MAID",
          coin_type: "OMNI",
          minimum_confirmation: 2,
          name: "MaidSafeCoin",
          transaction_fee: 2.0,
        },
        minimum_trade: 5.38329027,
        name: "BTC-MAID",
      },
      open_buy_orders: 132,
      open_sell_orders: 2682,
      previous_day: 2.985e-5,
      ticker: %Ticker{
        ask: 3.254e-5,
        bid: 3.235e-5,
        last: 3.254e-5,
      },
      volume: 1475892.39121387,
    }, %MarketSummary{
      base_volume: 10748.54649603,
      high: 4.977e-5,
      low: 3.53e-5,
      market: %Market{
        active: true,
        base_currency: %Currency{
          active: true,
          base_address: "1N52wHoVR79PMDishab2XmRHsbekCdGquK",
          code: "BTC",
          coin_type: "BITCOIN",
          minimum_confirmation: 2,
          name: "Bitcoin",
          transaction_fee: 0.001,
        },
        created_at: ~N[2014-03-03 09:00:00],
        market_currency: %Currency{
          active: true,
          base_address: "NXT-97H4-KRWL-A53G-7GVRG",
          code: "NXT",
          coin_type: "NXT",
          minimum_confirmation: 8,
          name: "NXT",
          transaction_fee: 2.0,
        },
        minimum_trade: 8.63557858,
        name: "BTC-NXT",
      },
      open_buy_orders: 3445,
      open_sell_orders: 8384,
      previous_day: 4.4e-5,
      ticker: %Ticker{
        ask: 4.251e-5,
        bid: 4.243e-5,
        last: 4.243e-5,
      },
      volume: 256505597.7027491,
    }, %MarketSummary{
      base_volume: 262.83760771,
      high: 5.6e-7,
      low: 4.4e-7,
      market: %Market{
        active: true,
        base_currency: %Currency{
          active: true,
          base_address: "1N52wHoVR79PMDishab2XmRHsbekCdGquK",
          code: "BTC",
          coin_type: "BITCOIN",
          minimum_confirmation: 2,
          name: "Bitcoin",
          transaction_fee: 0.001,
        },
        created_at: ~N[2016-02-17 22:42:03.61],
        market_currency: %Currency{
          active: true,
          base_address: nil,
          code: "XVG",
          coin_type: "BITCOIN",
          minimum_confirmation: 30,
          name: "Verge",
          transaction_fee: 0.2,
        },
        minimum_trade: 462.96296296,
        name: "BTC-XVG",
      },
      open_buy_orders: 995,
      open_sell_orders: 13007,
      previous_day: 5.0e-7,
      ticker: %Bittrex.Data.Ticker{
        ask: 5.6e-7,
        bid: 5.5e-7,
        last: 5.5e-7,
      },
      volume: 518359282.7773253,
    }, %MarketSummary{
      base_volume: 482.58344911,
      high: 0.0223772,
      low: 0.01651678,
      market: %Market{
        active: true,
        base_currency: %Currency{
          active: true,
          base_address: "1N52wHoVR79PMDishab2XmRHsbekCdGquK",
          code: "BTC",
          coin_type: "BITCOIN",
          minimum_confirmation: 2,
          name: "Bitcoin",
          transaction_fee: 0.001,
        },
        created_at: ~N[2016-10-28 17:13:10.833],
        market_currency: %Currency{
          active: true,
          base_address: "t1KVcK1PEFHRjzJTA3oeXA82tiUGj5V72Cb",
          code: "ZEC",
          coin_type: "BITCOINEX",
          minimum_confirmation: 20,
          name: "ZCash",
          transaction_fee: 0.005,
        },
        minimum_trade: 0.00853239,
        name: "BTC-ZEC",
      },
      open_buy_orders: 696,
      open_sell_orders: 10871,
      previous_day: 0.01761,
      ticker: %Ticker{
        ask: 0.0202965,
        bid: 0.02014008,
        last: 0.02014006,
      },
      volume: 24378.01097417,
    }, %MarketSummary{
      base_volume: 9.58688413,
      high: 8.4e-5,
      low: 7.5e-5,
      market: %Market{
        active: true,
        base_currency: %Currency{
          active: true,
          base_address: "1N52wHoVR79PMDishab2XmRHsbekCdGquK",
          code: "BTC",
          coin_type: "BITCOIN",
          minimum_confirmation: 2,
          name: "Bitcoin",
          transaction_fee: 0.001,
        },
        created_at: ~N[2014-12-12 19:51:07.703],
        market_currency: %Currency{
          active: true,
          base_address: nil,
          code: "FAIR",
          coin_type: "BITCOIN",
          minimum_confirmation: 10,
          name: "FairCoin",
          transaction_fee: 0.02,
        },
        minimum_trade: 2.3368854,
        name: "BTC-FAIR",
      },
      open_buy_orders: 109,
      open_sell_orders: 708,
      previous_day: 7.5e-5,
      ticker: %Ticker{
        ask: 7.725e-5,
        bid: 7.5e-5,
        last: 7.5e-5
      },
      volume: 124396.52333554,
    }, %MarketSummary{
      base_volume: 2.54916931,
      high: 3.257e-5,
      low: 2.901e-5,
      market: %Market{
        active: true,
        base_currency: %Currency{
          active: true,
          base_address: "1N52wHoVR79PMDishab2XmRHsbekCdGquK",
          code: "BTC",
          coin_type: "BITCOIN",
          minimum_confirmation: 2,
          name: "Bitcoin",
          transaction_fee: 0.001,
        },
        created_at: ~N[2014-05-13 09:00:00],
        market_currency: %Currency{
          active: true,
          base_address: nil,
          code: "CURE",
          coin_type: "BITCOIN",
          minimum_confirmation: 6,
          name: "CureCoin",
          transaction_fee: 0.0002,
        },
        minimum_trade: 7.14285714,
        name: "BTC-CURE",
      },
      open_buy_orders: 103,
      open_sell_orders: 1899,
      previous_day: 3.13e-5,
      ticker: %Ticker{
        ask: 2.965e-5,
        bid: 2.93e-5,
        last: 2.965e-5,
      },
      volume: 82911.04638579,
    }, %MarketSummary{
      base_volume: 18.63135479,
      high: 3.2e-4,
      low: 2.6501e-4,
      market: %Market{
        active: true,
        base_currency: %Currency{
          active: true,
          base_address: "1N52wHoVR79PMDishab2XmRHsbekCdGquK",
          code: "BTC",
          coin_type: "BITCOIN",
          minimum_confirmation: 2,
          name: "Bitcoin",
          transaction_fee: 0.001,
        },
        created_at: ~N[2017-03-23 00:48:15.94],
        market_currency: %Currency{
          active: true,
          base_address: "3P31zvGdh6ai6JK6zZ18TjYzJsa1B83YPoj",
          code: "TKS",
          coin_type: "WAVES_ASSET",
          minimum_confirmation: 20,
          name: "Tokes",
          transaction_fee: 0.1,
        },
        minimum_trade: 1.78788529,
        name: "BTC-TKS",
      },
      open_buy_orders: 190,
      open_sell_orders: 1335,
      previous_day: 3.061e-4,
      ticker: %Ticker{
        ask: 2.9259e-4,
        bid: 2.9218e-4,
        last: 2.9218e-4,
      },
      volume: 63406.07549542,
    }, %MarketSummary{
      base_volume: 175487125.41883156,
      high: 16198.7,
      low: 13560.0,
      market: %Market{
        active: true,
        base_currency: %Currency{
          active: true,
          base_address: "1DUb2YYbQA1jjaNYzVXLZ7ZioEhLXtbUru",
          code: "USDT",
          coin_type: "OMNI",
          minimum_confirmation: 2,
          name: "Tether",
          transaction_fee: 25.0,
        },
        created_at: ~N[2015-12-11 06:31:40.633],
        market_currency: %Currency{
          active: true,
          base_address: "1N52wHoVR79PMDishab2XmRHsbekCdGquK",
          code: "BTC",
          coin_type: "BITCOIN",
          minimum_confirmation: 2,
          name: "Bitcoin",
          transaction_fee: 0.001,
        },
        minimum_trade: 7.4074e-4,
        name: "USDT-BTC",
      },
      open_buy_orders: 8586,
      open_sell_orders: 6651,
      previous_day: 16120.39576595,
      ticker: %Ticker{
        ask: 1.41e4,
        bid: 14099.0,
        last: 1.41e4,
      },
      volume: 11928.33672876,
    }, %MarketSummary{
      base_volume: 25411.44592563,
      high: 1.2295e-4,
      low: 8.689e-5,
      market: %Market{
        active: true,
        base_currency: %Currency{
          active: true,
          base_address: "1N52wHoVR79PMDishab2XmRHsbekCdGquK",
          code: "BTC",
          coin_type: "BITCOIN",
          minimum_confirmation: 2,
          name: "Bitcoin",
          transaction_fee: 0.001,
        },
        created_at: ~N[2014-12-22 19:30:27.45],
        market_currency: %Currency{
          active: true,
          base_address: "rPVMhWBsfF9iMXYj3aAzJVkPDTFNSyWdKy",
          code: "XRP",
          coin_type: "RIPPLE",
          minimum_confirmation: 10,
          name: "Ripple",
          transaction_fee: 5.0,
        },
        minimum_trade: 5.35733419,
        name: "BTC-XRP",
      },
      open_buy_orders: 12252,
      open_sell_orders: 8744,
      previous_day: 9.152e-5,
      ticker: %Ticker{
        ask: 1.1022e-4,
        bid: 1.102e-4,
        last: 1.102e-4,
      },
      volume: 248973351.63068497,
    }, %MarketSummary{
      base_volume: 52410813.51447684,
      high: 1.71,
      low: 1.2071001,
      market: %Market{
        active: true,
        base_currency: %Currency{
          active: true,
          base_address: "1DUb2YYbQA1jjaNYzVXLZ7ZioEhLXtbUru",
          code: "USDT",
          coin_type: "OMNI",
          minimum_confirmation: 2,
          name: "Tether",
          transaction_fee: 25.0,
        },
        created_at: ~N[2017-07-14 17:10:10.737],
        market_currency: %Currency{
          active: true,
          base_address: "rPVMhWBsfF9iMXYj3aAzJVkPDTFNSyWdKy",
          code: "XRP",
          coin_type: "RIPPLE",
          minimum_confirmation: 10,
          name: "Ripple",
          transaction_fee: 5.0,
        },
        minimum_trade: 7.3534816,
        name: "USDT-XRP",
      },
      open_buy_orders: 3739,
      open_sell_orders: 1587,
      previous_day: 1.27300001,
      ticker: %Ticker{
        ask: 1.58899987,
        bid: 1.587,
        last: 1.58699999,
      },
      volume: 36533363.35324321,
    }, %MarketSummary{
      base_volume: 0.0,
      high: 0.0,
      low: 0.0,
      market: %Market{
        active: true,
        base_currency: %Currency{
          active: true,
          base_address: "1N52wHoVR79PMDishab2XmRHsbekCdGquK",
          code: "BTC",
          coin_type: "BITCOIN",
          minimum_confirmation: 2,
          name: "Bitcoin",
          transaction_fee: 0.0005,
        },
        created_at: ~N[2019-05-07 17:00:53.737],
        market_currency: %Currency{
          active: true,
          base_address: "0xfbb1b73c4f0bda4f67dca266ce6ef42f520fbb98",
          code: "WIB",
          coin_type: "ETH_CONTRACT",
          minimum_confirmation: 36,
          name: "Wibson",
          transaction_fee: 1.0,
        },
        minimum_trade: 6250.0,
        name: "BTC-WIB",
      },
      open_buy_orders: 25,
      open_sell_orders: 293,
      previous_day: 0.0,
      ticker: %Ticker{
        ask: 4.0e-8,
        bid: 3.0e-8,
        last: 0.0,
      },
      volume: 0.0,
    }]
  end

  defp open_orders do
    [%Order{
      cancel_initiated: false,
      closed_at: nil,
      condition: "NONE",
      condition_target: nil,
      conditional: false,
      immediate_or_cancel: false,
      market: %Market{
        name: "BTC-TKS",
      },
      opened_at: ~N[2017-12-24 16:23:37.867],
      order_type: "LIMIT_BUY",
      quantity: 2.53009068,
      quantity_remaining: 2.53009068,
      reserve_remaining: nil,
      reserved: nil,
    }, %Order{
      cancel_initiated: false,
      closed_at: nil,
      condition: "NONE",
      condition_target: nil,
      conditional: false,
      immediate_or_cancel: false,
      market: %Market{
        name: "BTC-XRP",
      },
      opened_at: ~N[2017-12-29 15:59:51.547],
      order_type: "LIMIT_BUY",
      quantity: 7.49783739,
      quantity_remaining: 7.49783739,
      reserve_remaining: nil,
      reserved: nil,
    }]
  end
end
